export enum PlayerDocumentType {
  INSURANCE = 'INSURANCE',
  PERSONAL_PHOTO = 'PERSONAL_PHOTO',
  NATIONAL_ID_OR_BIRTH_CERTIFICATE = 'NATIONAL_ID_OR_BIRTH_CERTIFICATE',
  PREVIOUS_CLUB_RELEASE = 'PREVIOUS_CLUB_RELEASE',
  PARENTAL_CONSENT = 'PARENTAL_CONSENT',
  OTHER = 'OTHER',
}
