services:
  postgres:
    image: postgres:16
    container_name: abshar-academy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: abshar_academy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - abshar_academy_postgres_data:/var/lib/postgresql/data

volumes:
  abshar_academy_postgres_data:
